In [1]:
import pandas as pd
import numpy as np

print("Environnement configuré avec succès !")
print("Version de Pandas :", pd.__version__)

Environnement configuré avec succès !
Version de Pandas : 2.3.3

In [2]:
import pandas as pd

path = "C:/Users/ADMIN/Downloads/student+performance/student/student-mat.csv"

df = pd.read_csv(path, sep=';')

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [4]:
import pandas as pd

path = "C:/Users/ADMIN/Downloads/student+performance/student/student-mat.csv"

df = pd.read_csv(path, sep=';')

print("Aperçu des données:")
display(df.head())

print("\nInformations sur le dataset:")
df.info()

Aperçu des données:

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

Informations sur le dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [5]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [6]:
import pandas as pd

url = "https://jsonplaceholder.typicode.com/posts"

df_json = pd.read_json(url)

df_json.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [7]:
import pandas as pd

url = "https://github.com/pandas-dev/pandas/raw/main/doc/data/titanic.xlsx"

df_excel = pd.read_excel(url)

df_excel.head()

HTTPError: HTTP Error 404: Not Found

In [8]:
import pandas as pd

url = "https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv"

df_excel = pd.read_csv(url)

df_excel.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
import pandas as pd 
import sqlite3

In [10]:
df = pd.read_csv("C:/Users/ADMIN/Downloads/student+performance/student/student-mat.csv", sep=";")

In [11]:
conn = sqlite3.connect("students.db")

In [12]:
df.to_sql("etudiants", conn, if_exists="replace", index=False)

395

In [13]:
G3 > 15

NameError: name 'G3' is not defined

In [14]:
query = "SELECT * FROM etudiants WHERE G3 > 15"

In [15]:
df_sql = pd.read_sql_query(query, conn)

df_sql.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
1,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
2,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
3,GP,M,15,U,GT3,T,4,4,services,services,...,4,3,1,1,1,5,0,17,16,17
4,GP,M,15,R,GT3,T,4,3,teacher,at_home,...,4,5,2,1,1,5,0,17,16,16

In [16]:
import requests
import pandas as pd

url = "https://jsonplaceholder.typicode.com/posts"

response = requests.get(url)

data = response.json()

df_api = pd.DataFrame(data)

df_api.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [17]:
import requests
from bs4 import BeautifulSoup

url = "https://example.com"

page = requests.get(url)

soup = BeautifulSoup(page.text, "html.parser")

titles = soup.find_all("h1")

for t in titles:
    print(t.text)

SSLError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1017)')))

In [18]:
import requests
from bs4 import BeautifulSoup

url = "http://example.com"

page = requests.get(url, verify=False)

soup = BeautifulSoup(page.text, "html.parser")

titles = soup.find_all("h1")

for t in titles:
    print(t.text)

Example Domain

In [19]:
final_df = pd.concat([df, df_sql, df_api], ignore_index=True)

final_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,Walc,health,absences,G1,G2,G3,userId,id,title,body
0,GP,F,18.0,U,GT3,A,4.0,4.0,at_home,teacher,...,1.0,3.0,6.0,5.0,6.0,6.0,NaN,NaN,NaN,NaN
1,GP,F,17.0,U,GT3,T,1.0,1.0,at_home,other,...,1.0,3.0,4.0,5.0,5.0,6.0,NaN,NaN,NaN,NaN
2,GP,F,15.0,U,LE3,T,1.0,1.0,at_home,other,...,3.0,3.0,10.0,7.0,8.0,10.0,NaN,NaN,NaN,NaN
3,GP,F,15.0,U,GT3,T,4.0,2.0,health,services,...,1.0,5.0,2.0,15.0,14.0,15.0,NaN,NaN,NaN,NaN
4,GP,F,16.0,U,GT3,T,3.0,3.0,other,other,...,2.0,5.0,4.0,6.0,10.0,10.0,NaN,NaN,NaN,NaN

In [20]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      435 non-null    object
 1   sex         435 non-null    object
 2   age         435 non-null    float64
 3   address     435 non-null    object
 4   famsize     435 non-null    object
 5   Pstatus     435 non-null    object
 6   Medu        435 non-null    float64
 7   Fedu        435 non-null    float64
 8   Mjob        435 non-null    object
 9   Fjob        435 non-null    object
 10  reason      435 non-null    object
 11  guardian    435 non-null    object
 12  traveltime  435 non-null    float64
 13  studytime   435 non-null    float64
 14  failures    435 non-null    float64
 15  schoolsup   435 non-null    object
 16  famsup      435 non-null    object
 17  paid        435 non-null    object
 18  activities  435 non-null    object
 19  nursery     435 non-null    object
 20  higher      435 non-null    object
 21  internet    435 non-null    object
 22  romantic    435 non-null    object
 23  famrel      435 non-null    float64
 24  freetime    435 non-null    float64
 25  goout       435 non-null    float64
 26  Dalc        435 non-null    float64
 27  Walc        435 non-null    float64
 28  health      435 non-null    float64
 29  absences    435 non-null    float64
 30  G1          435 non-null    float64
 31  G2          435 non-null    float64
 32  G3          435 non-null    float64
 33  userId      100 non-null    float64
 34  id          100 non-null    float64
 35  title       100 non-null    object
 36  body        100 non-null    object
dtypes: float64(18), object(19)
memory usage: 154.8+ KB

In [21]:
final_df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,userId,id
count,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,100.000000,100.000000
mean,16.668966,2.802299,2.547126,1.432184,2.050575,0.305747,3.956322,3.245977,3.094253,1.462069,2.255172,3.531034,5.579310,11.411494,11.264368,11.041379,5.500000,50.500000
std,1.273924,1.089326,1.094376,0.683494,0.854491,0.715747,0.900806,1.014504,1.122801,0.869509,1.290408,1.399746,7.809367,3.566143,4.000748,4.802374,2.886751,29.011492
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000,1.000000,1.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,9.000000,3.000000,25.750000
50%,17.000000,3.000000,3.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000,5.500000,50.500000
75%,18.000000,4.000000,4.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,14.000000,14.000000,15.000000,8.000000,75.250000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000,10.000000,100.000000